### ISSUE TITLE
demo error:AttributeError: 'ResNet' object has no attribute 'stages'

### ISSUE THREAD

**Issue by EstherJinyan** [open-mmlab/mmclassification#757]
Hello,when I run the test according to the tutorial, I found the following error, how can I solve it? thanks.

commd:
python demo/image_demo.py demo/demo.JPEG configs/resnet/resnet50_8xb32_in1k.py \
  https://download.openmmlab.com/mmclassification/v0/resnet/resnet50_8xb32_in1k_20210831-ea4938fc.pth
error:
Traceback (most recent call last):
  File "demo/image_demo.py", line 28, in <module>
    main()
  File "demo/image_demo.py", line 18, in main
    for i, stage in enumerate(model.backbone.stages):
  File "/root/miniconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1186, in __getattr__
    type(self).__name__, name))
AttributeError: 'ResNet' object has no attribute 'stages'

**Comment by mzr1996** [comment]
Get it, looks it's an unexpected modification on `image_demo.py`, I will fix it today.

**Comment by mzr1996** [comment]
Done, please pull the latest master branch.

**Comment by EstherJinyan** [comment]
Thank you, it can be run, but it has been running with no results, stopped at the interface below for ten minutes and still no results， is it normal?
>   https://download.openmmlab.com/mmclassification/v0/resnet/resnet50_8xb32_in1k_20210831-ea4938fc.pth
/root/miniconda3/envs/py37/lib/python3.7/site-packages/mmcv/cnn/bricks/transformer.py:32: UserWarning: Fail to import ``MultiScaleDeformableAttention`` from ``mmcv.ops.multi_scale_deform_attn``, You should install ``mmcv-full`` if you need this module. 
  warnings.warn('Fail to import ``MultiScaleDeformableAttention`` from '
load checkpoint from http path: https://download.openmmlab.com/mmclassification/v0/resnet/resnet50_8xb32_in1k_20210831-ea4938fc.pth

**Comment by EstherJinyan** [comment]
Thank you, there are no bugs, but the result is not running, it stays in the interface below, seems to keep loading the model.I try to download the model to the local and execute it again, the result is still the same.how can i solve this problem？

UserWarning: Fail to import ``MultiScaleDeformableAttention`` from ``mmcv.ops.multi_scale_deform_attn``, You should install ``mmcv-full`` if you need this module. 
  warnings.warn('Fail to import ``MultiScaleDeformableAttention`` from '
load checkpoint from local path: checkpoints/pretrained/resnet50_8xb32_in1k_20210831-ea4938fc.pth

**Comment by mzr1996** [comment]
> 

It won't output results, and it will plot the demo image and show it.
Are you using it on a server without GUI interface?
If you want to preview the results, you can replace the line `show_result_pyplot(model, args.img, result)` to `print(result)`

**Comment by EstherJinyan** [comment]
soga,thanks~
